services:
    _defaults:
        autowire: true
        autoconfigure: true

    Onisep\IbexaCustomSettingsBundle\:
        resource: '../../'

    Onisep\IbexaCustomSettingsBundle\Tab\IbexaCustomSettingsLocationTab:
        tags:
            - { name: 'ibexa.admin_ui.tab', group: 'location-view' }
